version: "3"

services:
  mariadb:
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql:rw
  php:
    #image: wodby/drupal:$DRUPAL_TAG
    #environment:
    #  PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./data/php:/var/www/html:rw,cached
      #- codebase:/var/www/html

  nginx:
    volumes:
      - ./data/php:/var/www/html:rw,cached
      #- codebase:/var/www/html

volumes:
  codebase:
  database:
